# eslint-disable yml/file-extension
policy:
  - section:
      - id:
          - does_this_contribute_to_the_maintenance_of_the_project
        block-list:
          - Nope
        label:
          - name: 🔧 maintenance
            keys:
              - Yep
      - id:
          - does_this_need_a_design
        block-list:
          - Nope
        label:
          - name: 💎 design
            keys:
              - Yep
      - id:
          - is_this_a_good_first_issue
        block-list:
          - Nope
        label:
          - name: good first issue
            keys:
              - Yep
