version: 2
updates:
  - directory: /
    labels:
      - 🔧 maintenance
    package-ecosystem: github-actions
    schedule:
      interval: monthly
  - directory: /
    labels:
      - 🔧 maintenance
    package-ecosystem: npm
    schedule:
      interval: monthly
  - directory: /packages/wisp-desktop
    labels:
      - 🔧 maintenance
    package-ecosystem: npm
    schedule:
      interval: monthly
  - directory: /packages/wisp-website
    labels:
      - 🔧 maintenance
    package-ecosystem: npm
    schedule:
      interval: monthly
