title: "[Bug]: "
name: Bug
description: Create a new bug issue.
type: bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - id: contact
    type: input
    attributes:
      description: How can we get in touch with you if we need more info?
      label: Contact Details
      placeholder: ex. email@example.com
    validations:
      required: false
  - id: what-happened
    type: textarea
    attributes:
      description: Also tell us, what did you expect to happen?
      label: What happened?
      placeholder: Tell us what you see!
      value: A bug happened!
    validations:
      required: true
  - id: version
    type: dropdown
    attributes:
      description: What version of our software are you running?
      default: 0
      label: Version
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
    validations:
      required: true
  - id: browsers
    type: dropdown
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - id: logs
    type: textarea
    attributes:
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      label: Relevant log output
      render: shell
  - id: terms
    type: checkboxes
    attributes:
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com).
      label: Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
projects:
  - spear-ai/41
