name: Feature
description: Create a feature request.
type: Feature
body:
  - type: dropdown
    id: is-maintenance
    attributes:
      label: Is maintenance
      description: Is this issue related to maintenance of the project?
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      placeholder: Type your description here…
projects:
  - spear-ai/41
