name: Feature
description: Create a feature issue.
type: Feature
body:
  - type: textarea
    attributes:
      label: Description
      placeholder: Type your description here…
projects:
  - spear-ai/41
