name: Feature
description: Create a feature request.
type: Feature
body:
  - id: is-good-first-issue
    type: dropdown
    attributes:
      description: e.g. An engineer who’s unfamiliar with the project could get started quickly.
      label: Is this a good first issue?
      options:
        - Nope
        - Yep
    validations:
      required: true
  - id: is-maintenance
    type: dropdown
    attributes:
      description: e.g. Dependency updates, Documentation, Refactoring, Developer productivity, etc.
      label: Does this contribute to the maintenance of the project?
      options:
        - Nope
        - Yep
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      placeholder: Type your description here…
  - id: is-design-required
    type: dropdown
    attributes:
      description: e.g. The Design Engineering team will help with the feature.
      label: Does this need a design?
      options:
        - Nope
        - Yep
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      placeholder: Type your description here…
projects:
  - spear-ai/41
