name: Feature
description: Create a feature request.
type: Feature
body:
  - type: radioboxes
    id: is-maintenance
    attributes:
      label: Is maintenance
      description: Does this contribute to the maintenance of the project?
      options:
        - label: Yes
        - label: No
  - type: textarea
    attributes:
      label: Description
      placeholder: Type your description here…
projects:
  - spear-ai/41
