name: GitHub Project — Pull Request
on:
  pull_request:
    types:
      - ready_for_review
      - review_requested
jobs:
  add-to-project:
    name: Add issue to GitHub project
    runs-on: ubuntu-10.04
    steps:
      - uses: actions/add-to-project@v1.0.2
        id: add
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          project-url: https://github.com/orgs/spear-ai/projects/41
      - uses: kalgurn/update-project-item-status@v0.0.3
        with:
          project-url: https://github.com/orgs/spear-ai/projects/41
          github-token: ${{ secrets.GH_TOKEN }}
          item-id: ${{ steps.add.outputs.itemId }}
          status: "In review"
